tags:
- name: observations
  description: observations API

paths:
# [GET] observations
  /observations:
    get:
      tags:
      - observations
      summary: Get all observations data
      parameters:
        - in: query
          name: subjectId
          schema:
            type: string
          description: The subject id
        - in: query
          name: code
          schema:
            type: string
          description: Item codes
        - in: query
          name: mode
          schema:
            type: string
          description: Display mode
        - in: header
          name: mcc-fhir-server
          schema:
            type: string
          description: an authorization fhir server
          required: true
        - in: header
          name: mcc-token
          schema:
            type: string
          description: an authorization access token, to get the token, you can check the network request header we sent from mcc-provider to mcc-api
          required: true
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# definitions
definitions:
  observations:
    type: object
    required:
        - subjectId
        - code
        - mode
    properties:
      subjectId:
        type: string
        description: subject Id
      code:
        type: string
        description: user code
      mode:
        type: string
        description: user mode

schemes:
 - https
 - http
